name: Nightly
run-name: ${{ github.actor }} triggered nightly on ${{ github.ref }}
on:
    schedule:
      # * is a special character in YAML so you have to quote this string
      - cron: '0 0 * * *'

    workflow_dispatch:
      inputs:
        push_results_to_gh_pages:
          description: "When set to true, the workflow pushes all benchmarking results to gh-pages UI "
          type: choice
          options:
              - 'true'
              - 'false'
          default: 'false'

# The scheduled job can't take inputs, but the workflow_dispatch jobs can. Resolve that
# discrepancy and store all the input arguments as environment variables.
env:
  PUSH_RESULTS_TO_GH_PAGES: "${{ github.event_name == 'schedule' || inputs.push_results_to_gh_pages }}"

jobs:

    # multi-gpu
    AWS-AVX2-192G-4-A10G-96G:
        uses: ./.github/workflows/nm-benchmark.yml
        with:
            label: aws-avx2-192G-4-a10g-96G
            benchmark_config_list_file:  ./.github/data/nm_benchmark_configs_list.txt
            timeout: 240
            gitref: '${{ github.ref }}'
            Gi_per_thread: 4
            python: "3.10.12"
            push_results_to_gh_pages: $PUSH_RESULTS_TO_GH_PAGES
        secrets: inherit

    # single gpu
    AWS-AVX2-32G-A10G-24G:
        uses: ./.github/workflows/nm-benchmark.yml
        with:
            label: aws-avx2-32G-a10g-24G
            benchmark_config_list_file:  ./.github/data/nm_benchmark_configs_list.txt
            timeout: 240
            gitref: '${{ github.ref }}'
            Gi_per_thread: 12
            python: "3.10.12"
            push_results_to_gh_pages: $PUSH_RESULTS_TO_GH_PAGES
        secrets: inherit
