name: nm-gh-action-benchmark
on:
  # makes workflow callable
  workflow_call:
    inputs:
      benchmark_results_artifact_name:
        description: 'benchmark results artifact to download and process'
        type: string
        required: true
      gitref:
        description: "git commit hash or branch name"
        type: string
        required: true
      timeout:
        description: "maximum time runner will be up"
        type: string
        required: true
      push_benchmark_results_to_gh_pages:
        description: "When set to true, the workflow pushes all benchmarking results to gh-pages UI "
        type: choice
        options:
            - 'true'
            - 'false'
        default: 'false'
      python:
        description: "python version, e.g. 3.10.12"
        type: string
        default: "3.10.12"

jobs:
  NM_GH_ACTION_BENCHMARK:

    runs-on: ubuntu-latest
    timeout-minutes: ${{ fromJSON(inputs.timeout) }}
    permissions:
      # Permissions required to be able to push to the nm-gh-pages branch 
      contents: write

    steps:
      - name: checkout repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.gitref }}
          submodules: recursive

      - name: download benchmark results artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.benchmark_results_artifact_name }}
          path: downloads

      - name: display structure of downloaded files
        run: ls -R ./downloads

      - name: setup python
        id: setup_python
        uses: actions/setup-python@v4
        with:
            python-version: ${{ inputs.python }} 

      # Produce GHA benchmark JSONs
      - name: make github-action-benchmark JSONs 
        uses: ./.github/actions/nm-produce-gha-benchmark-json
        with:
          vllm_benchmark_jsons_path: downloads 
          # Metrics that are "better" when the value is greater are stored here
          bigger_is_better_output_file_path: bigger_is_better.json
          # Metrics that are "better" when the value is smaller are stored here
          smaller_is_better_output_file_path: smaller_is_better.json

      - name: nm-github-action-benchmark(bigger_is_better.json)
        uses: ./.github/actions/nm-github-action-benchmark
        with:
          gh_action_benchmark_json_file_path:  "downloads/bigger_is_better.json"
          gh_action_benchmark_tool: "customBiggerIsBetter"
          # TODO (varun) - Switch this to `nm-gh-pages` after testing
          gh_pages_branch: "varun/generate-bench-results-test"
          auto_push: ${{ inputs.push_benchmark_results_to_gh_pages }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: nm-github-action-benchmark(smaller_is_better.json)
        uses: ./.github/actions/nm-github-action-benchmark
        with:
          gh_action_benchmark_json_file_path:  "downloads/smaller_is_better.json"
          gh_action_benchmark_tool: "customSmallerIsBetter"
          # TODO (varun) - Switch this to `nm-gh-pages` after testing
          gh_pages_branch: "varun/generate-bench-results-test"
          auto_push: ${{ inputs.push_benchmark_results_to_gh_pages }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
