name: remote push
run-name: ${{ github.actor }} verifying branch '${{ github.ref }}'
on:
  push:
    branches-ignore:
      - main

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:

    # multi-gpu
    BUILD-TEST:
        strategy:
            matrix:
                python: [3.10.12]
        uses: ./.github/workflows/build-test.yml
        with:
            build_label: aws-avx512-192G-4-T4-64G
            timeout: 240
            gitref: '${{ github.ref }}'
            Gi_per_thread: 4
            python: ${{ matrix.python }}
            test_skip_list: neuralmagic/tests/skip-for-remote-push.txt
        secrets: inherit
